version: "3.1"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./app/db:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:1.23.1
    container_name: nginx
    working_dir: /etc/nginx
    volumes:
      - ./app:/app
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${CSCART_PORT}:80"
      - "443:443"
    # depends_on:
    #   - php7.3
    #   - php7.4
    #   - php8.0

  php7.3:
    build:
      context: ./config/php7.3
      dockerfile: Dockerfile
    container_name: php7.3
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config/php7.3/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    environment:
        PHP_IDE_CONFIG: serverName=localhost
        CSCART_HOST: "php7.3.cs-cart.local:${CSCART_PORT}"

  php7.4:
    build:
      context: ./config/php7.4
      dockerfile: Dockerfile
    container_name: php7.4
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config/php7.4/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    environment:
        PHP_IDE_CONFIG: serverName=localhost
        CSCART_HOST: "php7.4.cs-cart.local:${CSCART_PORT}"
        XDEBUG_MODE: develop,debug
        XDEBUG_CONFIG:
          client_host=host.docker.internal
          start_with_request=yes
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php8.0:
    build:
      context: ./config/php8.0
      dockerfile: Dockerfile
    container_name: php8.0
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config/php8.0/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    environment:
        PHP_IDE_CONFIG: serverName=localhost
        CSCART_HOST: "php8.0.cs-cart.local:${CSCART_PORT}"

  pma:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: always
    ports:
      - 8081:80

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

# Change default subnet addresses (for uncomment - delete only '#'):
#networks:
#  default:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#      - subnet: 10.10.0.1/16

